<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>rho</string>
	</array>
	<key>name</key>
	<string>Rholang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>appl</key>
		<dict>
			<key>begin</key>
			<string>(?=\b\.?[-_'[:alnum:]]+\s*\()</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#argument-list</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.rho</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[-_'[:alnum:]]+</string>
				</dict>
			</array>
		</dict>
		<key>argument-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.open.rho</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.close.rho</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#terminals</string>
				</dict>
			</array>
		</dict>
		<key>bind</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.open.rho</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.close.rho</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parameter-bind</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminals</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;-|/:|:\\</string>
					<key>name</key>
					<string>keyword.other.bind.rho</string>
				</dict>
			</array>
		</dict>
		<key>block-declaration</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.open.rho</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.curlybrace.close.rho</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#declarations</string>
				</dict>
			</array>
		</dict>
		<key>case-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bcase\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bcase\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.case.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameter-bind</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#terminals</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=&gt;</string>
							<key>name</key>
							<string>keyword.control.case.rho</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&lt;-</string>
							<key>name</key>
							<string>keyword.other.case.rho</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>chan</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.chan.rho</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([@*#]*)([-_'[:alnum:]]+)</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rho</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.rho</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!/)///(?!/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.rho</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=$)</string>
							<key>name</key>
							<string>comment.block.documentation.rho</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!/)//(?!/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.rho</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=$)</string>
							<key>name</key>
							<string>comment.line.double-slash.rho</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Nil|true|false)\b</string>
					<key>name</key>
					<string>constant.language.rho</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.rho</string>
				</dict>
			</array>
		</dict>
		<key>contract-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bcontract\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bcontract\b</string>
					<key>name</key>
					<string>keyword.other.contract.rho</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([-_''[:alnum:]]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter-list</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\))</string>
							<key>end</key>
							<string>(?=\{)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\=</string>
									<key>name</key>
									<string>keyword.other.contract.rho</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#new-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contract-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#func-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#match-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#select-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#sum-total-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#appl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#chan</string>
				</dict>
			</array>
		</dict>
		<key>for-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bfor\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bfor\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.for.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bind</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>func-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bdef\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bdef\b</string>
					<key>name</key>
					<string>keyword.other.function.rho</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>([-_''[:alnum:]]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter-list</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;=\))</string>
							<key>end</key>
							<string>(?=\{)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\=</string>
									<key>name</key>
									<string>keyword.other.function.rho</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>match-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bmatch\b)</string>
			<key>end</key>
			<string>(?=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bmatch\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.match.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\bwith\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.match.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#terminals</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminals</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=&gt;</string>
					<key>name</key>
					<string>keyword.control.match.rho</string>
				</dict>
			</array>
		</dict>
		<key>new-declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bnew\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.new.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(in)\s*(?=\{)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.in.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.name.rho</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[-_'[:alnum:]]+</string>
		</dict>
		<key>parameter-bind</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.name.rho</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[-_'[:alnum:]]+\s*(?=&lt;-)</string>
		</dict>
		<key>parameter-list</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.open.rho</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.parenthesis.close.rho</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
			</array>
		</dict>
		<key>select-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\bselect\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bselect\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.select.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\})</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#case-declaration</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.rho</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rho</string>
				</dict>
			</array>
		</dict>
		<key>sum-total-declaration</key>
		<dict>
			<key>begin</key>
			<string>(?=\b(sum|total)\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(sum|total)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.sum.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bind</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-declaration</string>
				</dict>
			</array>
		</dict>
		<key>terminals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#appl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#chan</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rho</string>
	<key>uuid</key>
	<string>36a6a366-07fb-4659-ba3d-86cfc03c2f1e</string>
</dict>
</plist>
