<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rho</string>
	</array>
	<key>name</key>
	<string>Rholang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#proc</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.rho</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.rho</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!/)///(?!/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.rho</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=$)</string>
							<key>name</key>
							<string>comment.block.documentation.rho</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!/)//(?!/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.rho</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=$)</string>
							<key>name</key>
							<string>comment.line.double-slash.rho</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(_|Nil|true|false|Bool|Int|String|ByteArray|Uri|not|matches|and|or|Set)\b</string>
					<key>name</key>
					<string>constant.language.rho</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bundle.rho</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.rho</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(bundle)([+-0])?</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|else)\b</string>
					<key>name</key>
					<string>keyword.control.if.rho</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\||/\\|\\/|~|/|%%|\+|\-|\+\+|&lt;=|&lt;|&gt;=|&gt;|==|!=|&lt;-|=&gt;|\.\.\.</string>
					<key>name</key>
					<string>keyword.control.op.rho</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.rho</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)"</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.quote.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.rho</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.rho</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>contract</key>
		<dict>
			<key>begin</key>
			<string>(?=\bcontract\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bcontract\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.contract.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\{)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.rho</string>
								</dict>
							</dict>
							<key>match</key>
							<string>[-_'[:alnum:]]+</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\=</string>
							<key>name</key>
							<string>constant.language.contract.rho</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#proc</string>
				</dict>
			</array>
		</dict>
		<key>for</key>
		<dict>
			<key>begin</key>
			<string>(?=\bfor\b)</string>
			<key>end</key>
			<string>(?&lt;=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bfor\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.for.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#proc</string>
				</dict>
			</array>
		</dict>
		<key>match-select</key>
		<dict>
			<key>begin</key>
			<string>\b(match|select)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.match-select.rho</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\{)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#proc</string>
				</dict>
			</array>
		</dict>
		<key>new</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\bnew\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.new.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\bin\b</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.in.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#system-proc</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#parameter</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>parameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.rho</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.name.rho</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([@*]?)([-_'[:alnum:]]+)</string>
		</dict>
		<key>proc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#system-proc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#new</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#contract</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#for</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#match-select</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#proc-quote</string>
				</dict>
			</array>
		</dict>
		<key>proc-quote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@?)(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.quote.rho</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.open.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.close.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(!|!!)?(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.send.rho</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.open.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.close.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@?)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.quote.rho</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.open.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.close.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@?)(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.quote.rho</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.open.rho</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.parenthesis.close.rho</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#proc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.rho</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([@*])([-_'[:alnum:]]+)</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.rho</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rho</string>
				</dict>
			</array>
		</dict>
		<key>system-proc</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>constant.language.system.rho</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.rho</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rho</string>
	<key>uuid</key>
	<string>36a6a366-07fb-4659-ba3d-86cfc03c2f1e</string>
</dict>
</plist>
